# -*- coding: utf-8 -*-
"""master_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_D3KT6XImFM6r0UP23dESNJCMQWAku1A
"""

from agents.literature_agent import literature_analysis
from agents.clinical_agent import clinical_analysis
from agents.patent_agent import patent_analysis
from agents.mechanism_agent import mechanism_reasoning

def run_analysis(input_data):
    literature = literature_analysis(input_data)
    clinical = clinical_analysis(input_data)
    patent = patent_analysis(input_data)
    mechanism = mechanism_reasoning(input_data)

    return {
        "literature": literature,
        "clinical": clinical,
        "patent": patent,
        "mechanism": mechanism
    }